export const data = {
  products: [
    {
      id: "1",
      name: "Data Structures and Algorithms",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "DSA Course taught by BVT",
    },
    {
      id: "2",
      name: "Leetcode Top 50 Interview Questions",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: "IQs taught by BVT Engineers",
    },
    {
      id: "3",
      name: "NextJS and React Fundamentals for Web Development",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Intro to CS in JavaScript",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
